# File: docker-compose.yml
# Author: Dante Anzalone
# Description: Docker Compose configuration to serve a static website
#              using Nginx. Maps local website folder to container
#              and exposes port 8080 for development.

version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html
